# Generated by Django 6.0.3 on 2026-03-31 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "icon_name",
                    models.CharField(
                        blank=True,
                        help_text="Material symbol icon (e.g. 'map', 'hiking', 'auto_awesome', 'menu_book')",
                        max_length=50,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=150)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Kakheti, Svaneti", max_length=100
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        help_text="e.g., East Georgia, Highlands", max_length=100
                    ),
                ),
                ("image_url", models.URLField(max_length=500)),
                ("is_top_destination", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="FeaturedMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Drone Video Scenes", max_length=100),
                ),
                ("image_url", models.URLField(max_length=500)),
                ("video_url", models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="Unveiling the Soul of the Caucasus", max_length=255
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        default="Curated expeditions through Georgia's ancient valleys, hidden vineyards, and monolithic peaks."
                    ),
                ),
                (
                    "hero_image_url",
                    models.URLField(
                        help_text="Background image URL for the hero section",
                        max_length=500,
                    ),
                ),
                (
                    "about_text",
                    models.TextField(
                        default="A boutique travel studio specializing in deep-culture and high-adventure immersion across the Georgian Caucasus."
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(default="+995 555 010 203", max_length=20),
                ),
                ("facebook_url", models.URLField(blank=True, null=True)),
                ("instagram_url", models.URLField(blank=True, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Site Configuration",
                "verbose_name_plural": "Site Configurations",
            },
        ),
        migrations.CreateModel(
            name="Expedition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("price", models.IntegerField()),
                ("duration_days", models.IntegerField()),
                ("image_url", models.URLField(max_length=500)),
                ("is_featured", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.category",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.destination",
                    ),
                ),
            ],
        ),
    ]
