# Generated by Django 4.2.16 on 2026-04-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_article"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Journal Entry",
                "verbose_name_plural": "Journal Entries",
            },
        ),
        migrations.AlterModelOptions(
            name="booking",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Reservation",
                "verbose_name_plural": "Reservations",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Tour Type", "verbose_name_plural": "Tour Types"},
        ),
        migrations.AlterModelOptions(
            name="destination",
            options={
                "verbose_name": "Region & Location",
                "verbose_name_plural": "Regions & Locations",
            },
        ),
        migrations.AlterModelOptions(
            name="expedition",
            options={
                "verbose_name": "Tour & Expedition",
                "verbose_name_plural": "Tours & Expeditions",
            },
        ),
        migrations.AlterModelOptions(
            name="featuredmedia",
            options={
                "verbose_name": "Homepage Video Banner",
                "verbose_name_plural": "Homepage Video Banners",
            },
        ),
        migrations.AlterModelOptions(
            name="siteconfiguration",
            options={
                "verbose_name": "Global Site Branding & Settings",
                "verbose_name_plural": "Global Site Branding & Settings",
            },
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="contact_email",
            field=models.EmailField(
                default="hello@editorialexpedition.com", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="physical_address",
            field=models.CharField(default="Tbilisi, Georgia", max_length=255),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="site_name",
            field=models.CharField(default="The Editorial Expedition", max_length=100),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon_name",
            field=models.CharField(
                blank=True,
                help_text="Material symbol icon (e.g. 'hiking', 'wine_bar')",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="featuredmedia",
            name="title",
            field=models.CharField(default="Homepage Drone Scenes", max_length=100),
        ),
    ]
