# Generated by Django 4.2.16 on 2026-04-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_article_options_alter_booking_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="about_subtitle",
            field=models.TextField(
                default="We are an independent, boutique travel studio dedicated to curating unparalleled deep-culture immersions across the Georgian Caucasus."
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="about_title",
            field=models.CharField(default="About The Expedition", max_length=255),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="philosophy_content",
            field=models.TextField(
                default="We reject the mass-market approach to tourism. The Caucasus is not a checklist of monuments; it is a profound tapestry of ancient wisdom, rugged landscapes, and an unbroken lineage of hospitality."
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="philosophy_title",
            field=models.CharField(default="Our Philosophy", max_length=255),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="seo_description",
            field=models.TextField(
                default="High-end boutique travel and cultural expeditions across the Georgian Caucasus.",
                help_text="Site description for Google Search results.",
                max_length=300,
            ),
        ),
    ]
