# Generated by Django 4.2.16 on 2026-04-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_siteconfiguration_about_subtitle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="telegram_bot_token",
            field=models.CharField(
                blank=True,
                help_text="Bot Token from @BotFather",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Target Chat ID for notifications",
                max_length=100,
                null=True,
            ),
        ),
    ]
