# Generated by Django 4.2.16 on 2026-04-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_siteconfiguration_telegram_bot_token_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuickLead",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("phone_number", models.CharField(max_length=50)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Tour preference or specific question",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Home Page Lead",
                "verbose_name_plural": "Home Page Leads",
                "ordering": ["-created_at"],
            },
        ),
    ]
