# Generated by Django 6.0.3 on 2026-05-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_quicklead"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Tour Type",
                "verbose_name_plural": "Tour Types",
            },
        ),
        migrations.AlterModelOptions(
            name="destination",
            options={
                "ordering": ["name"],
                "verbose_name": "Region & Location",
                "verbose_name_plural": "Regions & Locations",
            },
        ),
        migrations.RemoveField(
            model_name="article",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="expedition",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="featuredmedia",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="hero_image_url",
        ),
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="ატვირთეთ სტატიის მთავარი სურათი",
                null=True,
                upload_to="articles/",
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="ატვირთეთ დესტინაციის სურათი",
                null=True,
                upload_to="destinations/",
            ),
        ),
        migrations.AddField(
            model_name="expedition",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="ატვირთეთ ტური-ს მთავარი სურათი",
                null=True,
                upload_to="expeditions/",
            ),
        ),
        migrations.AddField(
            model_name="featuredmedia",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="ატვირთეთ Thumbnail სურათი (ვიდეო ბანერის ფონი)",
                null=True,
                upload_to="featured/",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                help_text="ატვირთეთ Hero სექციის ფონური სურათი",
                null=True,
                upload_to="hero/",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="destination",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="expedition",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="featuredmedia",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="featuredmedia",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="YouTube ან Vimeo ლინკი (სურვილისამებრ)",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="quicklead",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
