# Generated by Django 6.0.3 on 2026-05-09 14:51

import django.core.validators
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_category_options_alter_destination_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="top_destinations_subtitle",
            field=models.CharField(
                default="The quintessential Georgian experience",
                max_length=255,
                verbose_name="ტოპ დესტინაციების ქვესათაური",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="top_destinations_title",
            field=models.CharField(
                default="Top Destinations",
                max_length=255,
                verbose_name="ტოპ დესტინაციების სათაური",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="tours_section_empty",
            field=models.CharField(
                default="No Expeditions Found",
                max_length=255,
                verbose_name="ტურების სექცია (როცა ტური არ მოიძებნა)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="tours_section_title",
            field=models.CharField(
                default="Curated Expeditions",
                max_length=255,
                verbose_name="ტურების სექციის სათაური",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("map", "Map"),
                    ("hiking", "Hiking"),
                    ("wine_bar", "Wine Bar"),
                    ("directions_car", "Car / Offroad"),
                    ("church", "Church / Culture"),
                    ("restaurant", "Restaurant / Food"),
                    ("hotel", "Hotel / Accommodation"),
                    ("photo_camera", "Photography"),
                    ("landscape", "Landscape"),
                    ("forest", "Forest / Nature"),
                    ("explore", "Explore"),
                ],
                help_text="Material symbol icon (e.g. 'hiking', 'wine_bar')",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="expedition",
            name="description",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="featuredmedia",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="YouTube ან Vimeo ლინკი (სურვილისამებრ)",
                max_length=500,
                validators=[
                    django.core.validators.RegexValidator(
                        message="მხოლოდ YouTube ან Vimeo ლინკებია დაშვებული.",
                        regex="^(https?\\:\\/\\/)?(www\\.)?(youtube\\.com|youtu\\.?be|vimeo\\.com)\\/.+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="about_subtitle",
            field=models.TextField(
                default="We are an independent, boutique travel studio dedicated to curating unparalleled deep-culture immersions across the Georgian Caucasus.",
                verbose_name="ჩვენს შესახებ ქვესათაური",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="about_title",
            field=models.CharField(
                default="About The Expedition",
                max_length=255,
                verbose_name="ჩვენს შესახებ სათაური",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                help_text="ატვირთეთ Hero სექციის ფონური სურათი",
                null=True,
                upload_to="hero/",
                verbose_name="მთავარი ფოტოსურათი (Hero Image)",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="hero_subtitle",
            field=models.TextField(
                default="Curated expeditions through Georgia's ancient valleys, hidden vineyards, and monolithic peaks.",
                verbose_name="მთავარი ქვესათაური (Hero Subtitle)",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="hero_title",
            field=models.CharField(
                default="Unveiling the Soul of the Caucasus",
                max_length=255,
                verbose_name="მთავარი სათაური (Hero Title)",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="philosophy_content",
            field=tinymce.models.HTMLField(
                default="We reject the mass-market approach to tourism...",
                verbose_name="ფილოსოფიის ტექსტი",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="philosophy_title",
            field=models.CharField(
                default="Our Philosophy",
                max_length=255,
                verbose_name="ფილოსოფიის სათაური",
            ),
        ),
    ]
