# Generated by Django 6.0.3 on 2026-05-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_siteconfiguration_top_destinations_subtitle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="featuredmedia",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="ატვირთეთ ვიდეო ფაილი (MP4) პირდაპირ.",
                null=True,
                upload_to="videos/",
            ),
        ),
        migrations.AlterField(
            model_name="featuredmedia",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="ან ჩასვით YouTube/Vimeo ლინკი (თუ ვიდეო ფაილს არ ტვირთავთ)",
                max_length=500,
            ),
        ),
    ]
