# Generated by Django 6.0.3 on 2026-05-09 15:02

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_featuredmedia_video_file_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "ბლოგის სტატია (Journal Entry)",
                "verbose_name_plural": "ბლოგის სტატიები (Journal Entries)",
            },
        ),
        migrations.AlterModelOptions(
            name="booking",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "ჯავშანი (Reservation)",
                "verbose_name_plural": "ჯავშნები (Reservations)",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "ტურის კატეგორია (Tour Type)",
                "verbose_name_plural": "ტურის კატეგორიები (Tour Types)",
            },
        ),
        migrations.AlterModelOptions(
            name="destination",
            options={
                "ordering": ["name"],
                "verbose_name": "რეგიონი და დესტინაცია (Region & Location)",
                "verbose_name_plural": "რეგიონები და დესტინაციები (Regions & Locations)",
            },
        ),
        migrations.AlterModelOptions(
            name="expedition",
            options={
                "verbose_name": "ტური და ექსპედიცია (Tour & Expedition)",
                "verbose_name_plural": "ტურები და ექსპედიციები (Tours & Expeditions)",
            },
        ),
        migrations.AlterModelOptions(
            name="featuredmedia",
            options={
                "verbose_name": "მთავარი გვერდის ვიდეო (Homepage Video Banner)",
                "verbose_name_plural": "მთავარი გვერდის ვიდეოები (Homepage Video Banners)",
            },
        ),
        migrations.AlterModelOptions(
            name="quicklead",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "მთავარი გვერდის მოთხოვნა (Home Page Lead)",
                "verbose_name_plural": "მთავარი გვერდის მოთხოვნები (Home Page Leads)",
            },
        ),
        migrations.AlterModelOptions(
            name="siteconfiguration",
            options={
                "verbose_name": "საიტის გლობალური პარამეტრები (Global Site Settings)",
                "verbose_name_plural": "საიტის გლობალური პარამეტრები (Global Site Settings)",
            },
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(
                default="Dispatch",
                help_text="e.g. Field Notes, Culture & Heritage",
                max_length=100,
                verbose_name="კატეგორია (Category)",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=tinymce.models.HTMLField(verbose_name="ტექსტი (Content)"),
        ),
        migrations.AlterField(
            model_name="article",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="შექმნის თარიღი (Created At)"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="ატვირთეთ სტატიის მთავარი სურათი",
                null=True,
                upload_to="articles/",
                verbose_name="მთავარი სურათი (Main Image)",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=255, verbose_name="სათაური (Title)"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="შექმნის თარიღი (Created At)"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="expedition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="core.expedition",
                verbose_name="ტური (Expedition)",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="full_name",
            field=models.CharField(
                max_length=200, verbose_name="სრული სახელი (Full Name)"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="group_size",
            field=models.PositiveIntegerField(
                default=1, verbose_name="ჯგუფის ზომა (Group Size)"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending — Awaiting Confirmation"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
                verbose_name="სტატუსი (Status)",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="total_price",
            field=models.IntegerField(verbose_name="ჯამური ფასი (Total Price)"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="travel_date",
            field=models.DateField(verbose_name="მოგზაურობის თარიღი (Travel Date)"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="მომხმარებელი (User)",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.CharField(
                blank=True,
                max_length=150,
                verbose_name="მოკლე აღწერა (Short Description)",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("map", "Map"),
                    ("hiking", "Hiking"),
                    ("wine_bar", "Wine Bar"),
                    ("directions_car", "Car / Offroad"),
                    ("church", "Church / Culture"),
                    ("restaurant", "Restaurant / Food"),
                    ("hotel", "Hotel / Accommodation"),
                    ("photo_camera", "Photography"),
                    ("landscape", "Landscape"),
                    ("forest", "Forest / Nature"),
                    ("explore", "Explore"),
                ],
                help_text="Material symbol icon (e.g. 'hiking', 'wine_bar')",
                max_length=50,
                verbose_name="აიქონი (Icon)",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="სახელი (Name)"),
        ),
        migrations.AlterField(
            model_name="destination",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="ატვირთეთ დესტინაციის სურათი",
                null=True,
                upload_to="destinations/",
                verbose_name="სურათი (Image)",
            ),
        ),
        migrations.AlterField(
            model_name="destination",
            name="is_top_destination",
            field=models.BooleanField(
                default=True, verbose_name="არის ტოპ დესტინაცია? (Is Top Destination?)"
            ),
        ),
        migrations.AlterField(
            model_name="destination",
            name="name",
            field=models.CharField(
                help_text="e.g., Kakheti, Svaneti",
                max_length=100,
                verbose_name="სახელი (Name)",
            ),
        ),
        migrations.AlterField(
            model_name="destination",
            name="region",
            field=models.CharField(
                help_text="e.g., East Georgia, Highlands",
                max_length=100,
                verbose_name="რეგიონი (Region)",
            ),
        ),
        migrations.AlterField(
            model_name="expedition",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.category",
                verbose_name="კატეგორია (Category)",
            ),
        ),
        migrations.AlterField(
            model_name="expedition",
            name="description",
            field=tinymce.models.HTMLField(verbose_name="აღწერა (Description)"),
        ),
        migrations.AlterField(
            model_name="expedition",
            name="duration_days",
            field=models.IntegerField(
                verbose_name="ხანგრძლივობა დღეებში (Duration in Days)"
            ),
        ),
        migrations.AlterField(
            model_name="expedition",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="ატვირთეთ ტური-ს მთავარი სურათი",
                null=True,
                upload_to="expeditions/",
                verbose_name="მთავარი სურათი (Main Image)",
            ),
        ),
        migrations.AlterField(
            model_name="expedition",
            name="is_featured",
            field=models.BooleanField(
                default=True, verbose_name="გამოჩნდეს მთავარ გვერდზე? (Is Featured?)"
            ),
        ),
        migrations.AlterField(
            model_name="expedition",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.destination",
                verbose_name="ლოკაცია (Location)",
            ),
        ),
        migrations.AlterField(
            model_name="expedition",
            name="price",
            field=models.IntegerField(verbose_name="ფასი (Price)"),
        ),
        migrations.AlterField(
            model_name="expedition",
            name="title",
            field=models.CharField(max_length=200, verbose_name="სათაური (Title)"),
        ),
        migrations.AlterField(
            model_name="featuredmedia",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="ატვირთეთ Thumbnail სურათი (ვიდეო ბანერის ფონი)",
                null=True,
                upload_to="featured/",
                verbose_name="ფონური სურათი (Thumbnail Image)",
            ),
        ),
        migrations.AlterField(
            model_name="featuredmedia",
            name="title",
            field=models.CharField(
                default="Homepage Drone Scenes",
                max_length=100,
                verbose_name="სათაური (Title)",
            ),
        ),
        migrations.AlterField(
            model_name="featuredmedia",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="ატვირთეთ ვიდეო ფაილი (MP4) პირდაპირ.",
                null=True,
                upload_to="videos/",
                verbose_name="ვიდეო ფაილი (Video File)",
            ),
        ),
        migrations.AlterField(
            model_name="featuredmedia",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="ან ჩასვით YouTube/Vimeo ლინკი (თუ ვიდეო ფაილს არ ტვირთავთ)",
                max_length=500,
                verbose_name="ვიდეოს ლინკი (Video URL)",
            ),
        ),
        migrations.AlterField(
            model_name="quicklead",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="შექმნის თარიღი (Created At)"
            ),
        ),
        migrations.AlterField(
            model_name="quicklead",
            name="full_name",
            field=models.CharField(
                max_length=200, verbose_name="სრული სახელი (Full Name)"
            ),
        ),
        migrations.AlterField(
            model_name="quicklead",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Tour preference or specific question",
                null=True,
                verbose_name="შენიშვნები/კითხვა (Notes)",
            ),
        ),
        migrations.AlterField(
            model_name="quicklead",
            name="phone_number",
            field=models.CharField(
                max_length=50, verbose_name="ტელეფონის ნომერი (Phone Number)"
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="about_subtitle",
            field=models.TextField(
                default="We are an independent, boutique travel studio dedicated to curating unparalleled deep-culture immersions across the Georgian Caucasus.",
                verbose_name="ჩვენს შესახებ ქვესათაური (About Subtitle)",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="about_text",
            field=models.TextField(
                default="A boutique travel studio specializing in deep-culture and high-adventure immersion across the Georgian Caucasus.",
                verbose_name="ფუტერის ტექსტი (Footer Text)",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="about_title",
            field=models.CharField(
                default="About The Expedition",
                max_length=255,
                verbose_name="ჩვენს შესახებ სათაური (About Title)",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="contact_email",
            field=models.EmailField(
                default="hello@editorialexpedition.com",
                max_length=254,
                verbose_name="საკონტაქტო ელ-ფოსტა (Contact Email)",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="facebook_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Facebook ლინკი (Facebook URL)"
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="instagram_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Instagram ლინკი (Instagram URL)"
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="linkedin_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="LinkedIn ლინკი (LinkedIn URL)"
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="philosophy_content",
            field=tinymce.models.HTMLField(
                default="We reject the mass-market approach to tourism...",
                verbose_name="ფილოსოფიის ტექსტი (Philosophy Content)",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="philosophy_title",
            field=models.CharField(
                default="Our Philosophy",
                max_length=255,
                verbose_name="ფილოსოფიის სათაური (Philosophy Title)",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="physical_address",
            field=models.CharField(
                default="Tbilisi, Georgia",
                max_length=255,
                verbose_name="მისამართი (Physical Address)",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="seo_description",
            field=models.TextField(
                default="High-end boutique travel and cultural expeditions across the Georgian Caucasus.",
                help_text="Site description for Google Search results.",
                max_length=300,
                verbose_name="SEO აღწერა (SEO Description)",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="site_name",
            field=models.CharField(
                default="The Editorial Expedition",
                max_length=100,
                verbose_name="საიტის სახელი (Site Name)",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="telegram_bot_token",
            field=models.CharField(
                blank=True,
                help_text="Bot Token from @BotFather",
                max_length=255,
                null=True,
                verbose_name="ტელეგრამ ბოტის ტოკენი (Telegram Bot Token)",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Target Chat ID for notifications",
                max_length=100,
                null=True,
                verbose_name="ტელეგრამ ჩატის ID (Telegram Chat ID)",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="top_destinations_subtitle",
            field=models.CharField(
                default="The quintessential Georgian experience",
                max_length=255,
                verbose_name="ტოპ დესტინაციების ქვესათაური (Top Destinations Subtitle)",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="top_destinations_title",
            field=models.CharField(
                default="Top Destinations",
                max_length=255,
                verbose_name="ტოპ დესტინაციების სათაური (Top Destinations Title)",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="tours_section_empty",
            field=models.CharField(
                default="No Expeditions Found",
                max_length=255,
                verbose_name="ტურების სექცია - როცა ტური არ მოიძებნა (Tours Empty State)",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="tours_section_title",
            field=models.CharField(
                default="Curated Expeditions",
                max_length=255,
                verbose_name="ტურების სექციის სათაური (Tours Section Title)",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="whatsapp_number",
            field=models.CharField(
                default="+995 555 010 203",
                max_length=20,
                verbose_name="WhatsApp ნომერი (WhatsApp Number)",
            ),
        ),
    ]
