# Generated by Django 6.0.3 on 2026-06-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_article_options_alter_booking_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expedition",
            name="discount_price",
            field=models.IntegerField(
                blank=True,
                help_text="დატოვეთ ცარიელი, თუ ფასდაკლება არ არის",
                null=True,
                verbose_name="ფასდაკლებული ფასი (Discount Price)",
            ),
        ),
    ]
