# Generated by Django 6.0.3 on 2026-07-18 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_expedition_discount_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="site_logo",
            field=models.ImageField(
                blank=True,
                help_text="ატვირთეთ საიტის ლოგო",
                null=True,
                upload_to="logo/",
                verbose_name="საიტის ლოგო (Site Logo)",
            ),
        ),
        migrations.CreateModel(
            name="ItineraryDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_number",
                    models.PositiveIntegerField(verbose_name="დღე (Day Number)"),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="სათაური (Title)"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ლოკაცია (Location)"
                    ),
                ),
                ("description", models.TextField(verbose_name="აღწერა (Description)")),
                (
                    "schedule",
                    models.TextField(
                        blank=True,
                        help_text="ხაზ-ხაზად, მაგ:\n14:00 - Airport Pickup\n15:00 - Hotel Check-in",
                        verbose_name="განრიგი (Schedule)",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="itinerary/",
                        verbose_name="სურათი (Image)",
                    ),
                ),
                (
                    "expedition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itinerary_days",
                        to="core.expedition",
                        verbose_name="ტური (Expedition)",
                    ),
                ),
            ],
            options={
                "verbose_name": "მარშრუტის დღე (Itinerary Day)",
                "verbose_name_plural": "მარშრუტის დღეები (Itinerary Days)",
                "ordering": ["day_number"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="სახელი (Full Name)"),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        default=5, verbose_name="რეიტინგი (Rating)"
                    ),
                ),
                ("comment", models.TextField(verbose_name="კომენტარი (Comment)")),
                (
                    "country_code",
                    models.CharField(
                        blank=True,
                        help_text="მაგ. GE, DE, US, FR, UA",
                        max_length=10,
                        verbose_name="ქვეყნის კოდი (Country Code)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="შექმნის თარიღი (Created At)"
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=True, verbose_name="აქტიურია? (Is Approved?)"
                    ),
                ),
                (
                    "expedition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="core.expedition",
                        verbose_name="ტური (Expedition)",
                    ),
                ),
            ],
            options={
                "verbose_name": "შეფასება (Review)",
                "verbose_name_plural": "შეფასებები (Reviews)",
                "ordering": ["-created_at"],
            },
        ),
    ]
